increased timeout + debug

diff --git a/ecs-deploy b/ecs-deploy
--- a/ecs-deploy
+++ b/ecs-deploy
@@ -8,7 +8,7 @@ MAX_DEFINITIONS=0
 IMAGE=false
 MIN=false
 MAX=false
-TIMEOUT=90
+TIMEOUT=600
 VERBOSE=false
 TAGVAR=false
 TAGONLY=""
@@ -400,6 +400,7 @@ function waitForGreenDeployment {
     if [[ "${ENABLE_ROLLBACK}" != "false" ]]; then
       rollback
     fi
+    >&2 echo "Error: Service deployment NOT successful within $TIMEOUT"
     exit 1
   fi
 }
